name: Create and publish a Docker image

on:
  workflow_dispatch:
#  pull_request:
#  push:
#    branches: master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: $

jobs:
  build-image:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    permissions:
      contents: read
      packages: write

    name: ${{ matrix.config.r }}

    strategy:
      fail-fast: false
      matrix:
        config:
#        - { r: 'devel' }
#        - { r: 'next'  }
        - { r: '4.3.2' }
#        - { r: '4.2.3' }
#        - { r: '4.1.3' }
#        - { r: '4.0.5' }
#        - { r: '3.6.3' }
#        - { r: '3.5.3' }

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Log in to the Container registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: $
      #     username: $
      #     password: $

      # - name: Docker Metadata
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: $/$

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: $
      #     labels: $